all:
  children:
    web:
      hosts:
        web1:
          ansible_host: 34.220.239.19
        web2:
          ansible_host: 34.220.58.179
      vars:
        ansible_user: admin
        ansible_ssh_private_key_file: ~/.ssh/aws
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
